api/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import ProdutoViewSet, PedidoViewSet, CarrinhoPedidoViewSet, VendaViewSet, CarrinhoVendaViewSet, \
    get_detail_produtos, api_home, ProdutoListApi, post_realiza_vendas, post_realiza_compras

router = routers.DefaultRouter()
router.register('produto', ProdutoViewSet)
router.register('pedido', PedidoViewSet)
router.register('carrinho-pedido', CarrinhoPedidoViewSet)
router.register('venda', VendaViewSet)
router.register('carrinho-venda', CarrinhoVendaViewSet)

urlpatterns = [
    path('drf/', include(router.urls)),
    path('', api_home, name='api_http'),
    path('produtos/', ProdutoListApi.as_view(), name='produto'),
    path('produto/<str:pk>', get_detail_produtos, name='get_produto'),
    path('produto/realiza_vendas/', post_realiza_vendas, name='post_realiza_vendas'),
    path('produto/realiza_compras/', post_realiza_compras, name='post_realiza_compras'),
    path('produto/', get_detail_produtos, name='get_produto'),
    path('api-auth/', include('rest_framework.urls'))

]

controle_estoque/urls.py
from django.urls import path
from .views import detalhe_produto, lista_produtos, modal_remove_produto, modal_cria_produto, modal_atualiza_produto

urlpatterns = [
    path('lista-produtos/', lista_produtos, name="lista-produtos"),
    path('detalhe-produto/<int:pk>', detalhe_produto, name='detalhe_produto'),
    path("modal-cria-produto/", modal_cria_produto, name="modal-cria-produto"),
    path('modal-atualiza-produto/<int:pk>', modal_atualiza_produto, name='modal-atualiza-produto'),
    path('modal-remove-produto/<int:pk>', modal_remove_produto, name='modal-remove-produto'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import settings  # visualizar img
from django.conf.urls.static import static  # visualizar img

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('interfaces.urls')),
    path('api-rest/', include('api.urls')),
    path('vendas/', include('controle_vendas.urls')),
    path('pedidos/', include('controle_pedidos.urls')),
    path('produtos/', include('controle_estoque.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

controle_estoque/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import User
from core.utils import GENERO_CHOICES, TAMANHO_CHOICES


class Fornecedor(models.Model):
    nome_empresa = models.CharField(unique=True, max_length=150)
    cnpj = models.CharField('CNPJ', max_length=14, help_text='Preencha o campo apenas com números.', validators=[
        RegexValidator(r'^\d{14,14}$', message='Por favor, não insira letras, " . " , " - " e " / " no campo abaixo.')])
    telefone = models.CharField(max_length=11, help_text='Preencha o campo apenas com números.', validators=[
        RegexValidator(r'^\d{10,11}$', message='Por favor, insira apenas os números do telefone.')])
    endereco = models.CharField(max_length=300)
    pessoa_contato = models.CharField(max_length=100)
    email = models.EmailField(max_length=120)
    ativo = models.BooleanField(default=True)
    faturamento_minimo = models.IntegerField(default=1000)

    def __str__(self):
        return self.nome_empresa

    class Meta:
        verbose_name = 'Fornecedor'
        verbose_name_plural = 'Fornecedores'
        ordering = ['nome_empresa']


class Categoria(models.Model):
    categoria = models.CharField(unique=True, max_length=30)
    codigo = models.CharField(max_length=3, unique=True)

    def __str__(self):
        return f'{self.categoria}'

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['categoria']

    def save(self, *args, **kwargs):
        self.categoria = self.categoria.title()
        self.codigo = self.codigo.upper()
        super(Categoria, self).save(*args, **kwargs)


class Subcategoria(models.Model):
    subcategoria = models.CharField(unique=True, max_length=30)
    codigo = models.CharField(unique=True, max_length=3)

    def __str__(self):
        return f'{self.subcategoria}'

    class Meta:
        verbose_name = 'Subcategoria'
        verbose_name_plural = 'Subcategorias'
        ordering = ['subcategoria']

    def save(self, *args, **kwargs):
        self.subcategoria = self.subcategoria.title()
        self.codigo = self.codigo.upper()
        super(Subcategoria, self).save(*args, **kwargs)


class Produto(models.Model):
    descricao = models.CharField(max_length=50)
    genero = models.CharField(choices=GENERO_CHOICES, max_length=255)
    categoria = models.ForeignKey("Categoria", on_delete=models.PROTECT)
    subcategoria = models.ForeignKey("Subcategoria", on_delete=models.PROTECT)
    tamanho = models.CharField("Tamanho", choices=TAMANHO_CHOICES, max_length=5)
    cor = models.CharField(max_length=30)
    min_pecas = models.PositiveSmallIntegerField()
    alerta_min = models.PositiveSmallIntegerField()
    limite_alerta_min = models.BooleanField(default=False, editable=False)
    total_pecas = models.PositiveSmallIntegerField()
    preco_compra = models.DecimalField(max_digits=6, decimal_places=2)
    preco_venda = models.DecimalField(max_digits=6, decimal_places=2)
    motivo_alteracao_preco = models.CharField(max_length=300, null=True)
    auto_pedido = models.BooleanField(default=False)
    ean = models.CharField(unique=True, max_length=13, editable=False)
    sku = models.CharField(max_length=11, editable=False)   # adicionar na prox sprint unique=True
    fornecedor = models.ForeignKey("Fornecedor", on_delete=models.PROTECT)
    criado_por = models.ForeignKey(User, on_delete=models.PROTECT, related_name='produto_criado_por', editable=False)
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_por = models.ForeignKey(User, on_delete=models.PROTECT,
                                       related_name='produto_atualizado_por', editable=False, null=True, blank=True)
    atualizado_em = models.DateTimeField(auto_now=True)
    ativo = models.BooleanField(default=True)
    em_compra = models.BooleanField(default=False, help_text='Para processo de compras')

    def __str__(self):
        return f'{self.descricao} {self.tamanho} - ean: {self.ean}'.title()

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['-id']


class HistoricoAtualizacaoPrecos(models.Model):
    produto = models.ForeignKey("controle_estoque.Produto", on_delete=models.PROTECT,
                                related_name='hist_preco_produto')
    descricao = models.CharField(max_length=30)
    preco_compra = models.DecimalField(max_digits=6, decimal_places=2)
    preco_venda = models.DecimalField(max_digits=6, decimal_places=2)
    motivo_alteracao_preco = models.CharField(max_length=300)
    criado_por = models.ForeignKey(User, on_delete=models.PROTECT, related_name='hist_preco_criado_por',
                                   editable=False)
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_por = models.ForeignKey(User, on_delete=models.PROTECT,
                                       related_name='hist_atualizado_por', editable=False, null=True, blank=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.produto.ean}'

    class Meta:
        verbose_name = 'Historico de Atualização de Preços'
        verbose_name_plural = 'Historico de Atualização de Preços'
        ordering = ['-criado_em']

controle_estoque/forms.py
from django import forms
from controle_estoque.models import Produto


class ProdutoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProdutoForm, self).__init__(*args, **kwargs)
        self.fields['preco_compra'] = forms.DecimalField(max_digits=6, decimal_places=2, min_value=0.01,
                                                         label="Preço de Compra")
        self.fields['preco_venda'] = forms.DecimalField(max_digits=6, decimal_places=2, min_value=0.01,
                                                        label="Preço de Venda")
        self.fields['total_pecas'] = forms.IntegerField(min_value=0, label="Total de Peças")
        self.fields['min_pecas'] = forms.IntegerField(min_value=0, label="Mín. de Peças")
        self.fields['descricao'] = forms.CharField(label="Descrição")
        self.fields['motivo_alteracao_preco'] = forms.CharField(label="Motivo Alteração de Preço")
        self.fields['alerta_min'] = forms.IntegerField(label="Alerta Mín.")

    class Meta:
        model = Produto
        fields = ['descricao', 'genero', 'categoria', 'subcategoria', 'tamanho', 'cor', 'min_pecas', 'alerta_min',
                  'total_pecas', 'preco_compra', 'preco_venda', 'motivo_alteracao_preco', 'fornecedor', 'auto_pedido']

controle_estoque/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from controle_estoque.models import Produto
from controle_estoque.forms import ProdutoForm


@login_required()
def lista_produtos(request):
    context = {
        "produtos": Produto.objects.filter(ativo=True),
        "active": "lista-produtos"
    }
    return render(request, 'lista_produtos.html', context)


@login_required()
def detalhe_produto(request, pk):
    context = {
        'produto': Produto.objects.get(pk=pk),
    }
    return render(request, 'modal_detalhe_produto.html', context)


@login_required()
@user_passes_test(lambda u: u.funcionario.is_manager_or_analyst(), login_url="/", redirect_field_name=None)
def modal_cria_produto(request):
    form = ProdutoForm(request.POST or None)
    if form.is_valid():
        form.instance.criado_por = request.user
        form.save()
        return redirect(reverse('lista-produtos'))
    return render(request, 'modal_cria_produto.html', {'form': form})


@login_required()
@user_passes_test(lambda u: u.funcionario.is_manager_or_analyst(), login_url="/", redirect_field_name=None)
def modal_atualiza_produto(request, pk):
    produto = get_object_or_404(Produto, pk=pk)
    form = ProdutoForm(request.POST or None, instance=produto)
    if form.is_valid():
        produto.atualizado_por = request.user
        produto.save()
        return redirect(reverse('lista-produtos'))
    return render(request, 'modal_atualiza_produto.html', {'form': form})


@login_required()
@user_passes_test(lambda u: u.funcionario.is_manager_or_analyst(), login_url="/", redirect_field_name=None)
def modal_remove_produto(request, pk):
    produto = get_object_or_404(Produto, pk=pk)
    if request.POST:
        produto.atualizado_por = request.user
        produto.ativo = False
        produto.save()
        return redirect(reverse('lista-produtos'))
    else:
        return render(request, 'modal_remove_produto.html', {'produto': produto})

controle_estoque/templates/lista_produtos.html
{% extends 'base.html' %}
{% block content %}
    <div class="card">
        <div class="card-header">
            <div style="display: flex; align-items: center; justify-content: space-between">
                <h3 class="text-darker">Listagem de Produtos</h3>
                {% if perms.controle_estoque.add_produto %}
                    <a href="#" onclick="open_modal('{% url 'modal-cria-produto' %}')">
                        <button class="btn btn-info mr-2" type="submit">Criar Novo Produto</button>
                    </a>
                {% endif %}
            </div>
        </div>
        <div class="card-body">
            <table class="table table-responsive-lg" id="table_produtos">
                <thead class="thead-light">
                <tr>
                    <th class="text-center">Produto</th>
                    <th>categoria</th>
                    <th>subcategoria</th>
                    <th>tamanho</th>
                    <th>Cor</th>
                    <th>total_pecas</th>
                    <th>EAN</th>
                    <th>SKU</th>
                    <th>Estoque</th>
                    <th>Criado Em</th>
                    {% if perms.controle_estoque.change_produto %}
                        <th class="text-center">Ações</th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for produto in produtos %}
                    <tr>
                        <td>
                            <a href="#" onclick="open_modal('{% url 'detalhe_produto' produto.id %}')">
                                Produto {{ produto.ean }}
                            </a>
                        </td>
                        <td> {{ produto.categoria }}</td>
                        <td> {{ produto.subcategoria }}</td>
                        <td> {{ produto.tamanho }}</td>
                        <td> {{ produto.cor }}</td>
                        <td> {{ produto.total_pecas }}</td>
                        <td> {{ produto.ean }}</td>
                        <td> {{ produto.sku }}</td>
                        {% if produto.limite_alerta_min %}
                            <td class="text-center"><i class="fa fa-check text-success"></i></td>
                        {% else %}
                            <td class="text-center"><i class="fa fa-exclamation text-danger"></i></td>
                        {% endif %}
                        <td> {{ produto.criado_em }}</td>


                        {% if user.funcionario.is_manager %}
                            <td style="display: flex; justify-content: space-between">
                                <a href="#" onclick="open_modal('{% url 'modal-atualiza-produto' produto.id %}')">
                                    <i class="fa fa-edit text-info"></i></a>
                                <a href="#" onclick="open_modal('{% url 'modal-remove-produto' produto.id %}')">
                                    <i class="fa fa-trash text-danger"></i></a>
                            </td>
                        {% elif user.funcionario.is_analyst %}
                            <td class="text-center">
                                <a href="#" onclick="open_modal('{% url 'modal-atualiza-produto' produto.id %}')">
                                    <i class="fa fa-edit text-info"></i></a>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="modal fade center" id="open-modal" tabindex="-1" role="dialog"></div>
{% endblock %}
{% block extrajs %}
    <script>
        function open_modal(url) {
            $('#open-modal').focus().load(url, function () {
                $(this).modal('show');
            })
        }

        $(document).ready(function () {
            $('#table_produtos').DataTable({
                "language": {
                    "lengthMenu": "Listando _MENU_ registros por pagina",
                    "zeroRecords": "Nenhum registro localizado",
                    "info": "Pagina _PAGE_ de _PAGES_",
                    "infoEmpty": "Nenhum registro disponível",
                    "infoFiltered": "(Filtrado de _MAX_ total resultados)",
                    "search": "Buscar",
                    "paginate": {
                        "first": "Primeira",
                        "last": "Ultima",
                        "next": "Proxima",
                        "previous": "Anterior"
                    },
                }
            });
        });
    </script>
{% endblock %}

controle_estoque/templates/modal_atualiza_produto.html
{% load static %}
{% load widget_tweaks %}
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header text-center">
            <h3 class="modal-title">Atualizar {{ form.instance }}</h3>
            <button type="button" class="close" data-dismiss="modal">
                <span class="text-danger">x</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="container mt-lg-4">
                <div class="col-md-12">
                    <form action="{% url 'modal-atualiza-produto' form.instance.id %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row mt-lg-3">
                            {% for field in form %}
                                <div class="col-md-4 mb-4">
                                    <label for="{{ field.auto_id }}"><strong>{{ field.label }}</strong></label>
                                    {% render_field field class="form-control" %}
                                    {{ field.errors }}
                                </div>
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-info mr-2">Salvar</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="modal-footer mb-5">
            <div class="row mt-5" style="position: absolute; right: 2em">
                <button type="submit" class="btn btn-info mr-2" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

controle_estoque/templates/modal_cria_produto.html
{% load static %}
{% load widget_tweaks %}
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header text-center">
            <h3 class="modal-title">Cadastrar Novo Produto</h3>
            <button type="button" class="close" data-dismiss="modal">
                <span class="text-danger">x</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="container mt-lg-4">
                <div class="col-md-12">
                    <form action="{% url 'modal-cria-produto' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row mt-lg-3">
                            {% for field in form %}
                                <div class="col-md-4 mb-4">
                                    <label for="{{ field.auto_id }}"><strong>{{ field.label }}</strong></label>
                                    {% render_field field class="form-control" %}
                                    {{ field.errors }}
                                </div>
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-info mr-2">Salvar</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="modal-footer mb-5">
            <div class="row mt-5" style="position: absolute; right: 2em">
                <button type="submit" class="btn btn-info mr-2" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

controle_estoque/templates/modal_detalhe_produto.html
{% load static %}
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header text-center">
            <h3 class="modal-title">Produto: {{produto}}</h3>
            <button type="button" class="close" data-dismiss="modal">
                <span class="text-danger">x</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="container mt-lg-4">
                <div class="col-md-12">
                    <div class="row mt-lg-3">
                        <div class="col-md-6 mb-4">
                            <h4>Descrição</h4>
                            {% if produto.descricao == "" %}
                            <p>Sem Descrição</p>
                            {% else %}
                            <p>{{produto.descricao}}</p>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Gênero</h4>
                            <p>{{produto.genero|title}}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Categoria</h4>
                            <p>{{produto.categoria}}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Sub Categoria</h4>
                            <p>{{produto.subcategoria}}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Tamanho</h4>
                            <p>{{produto.tamanho}}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Cor</h4>
                            <p>{{produto.cor}}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Mínimo de Peças em Estoque</h4>
                            <p>{{produto.min_pecas}}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Alerta Mínimo de Peças</h4>
                            <p>{{produto.alerta_min}}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Limite Alerta Mínimo de Peças</h4>
                            {% if produto.limite_alerta_min %}
                            <i class="fa fa-check-circle text-success"></i>
                            {% else%}
                            <i class="fa fa-times-circle text-danger"></i>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Total Peças em Estoque</h4>
                            <p>{{produto.total_pecas}}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Preço Compra</h4>
                            <p>R$ {{produto.preco_compra}}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Preço Venda</h4>
                            <p>R$ {{produto.preco_venda}}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Pedido Automático </h4>
                            {% if produto.auto_pedido %}
                            <i class="fa fa-check-circle text-success"></i>
                            {% else%}
                            <i class="fa fa-times-circle text-danger"></i>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>EAN</h4>
                            <p>{{produto.ean}}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>SKU</h4>
                            <p>{{produto.sku}}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Fornecedor</h4>
                            <p>{{produto.fornecedor}}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Criado Por:</h4>
                            <p>{{produto.criado_por|title}}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Data Criação:</h4>
                            <p>{{produto.criado_em}}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Atualizado Por:</h4>
                            {% if produto.atualizado_por == None %}
                            <p> Sem Atualização</p>
                            {% else %}
                            <p>{{produto.atualizado_por|title}}</p>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Ultima Atualização:</h4>
                            {% if produto.atualizado_por == None %}
                            <p> Sem Atualização</p>
                            {% else %}
                            <p>{{produto.atualizado_em}}</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer mb-5">
            <div class="row mt-5" style="position: absolute; right: 2em">
                <button type="submit" class="btn btn-info mr-2" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

controle_estoque/templates/modal_remove_produto.html
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title">Confirmação da exclusão</h3>
            <button type="button" class="close" data-dismiss="modal">
                <span>x</span>
            </button>
        </div>
        <div class="modal-body">
            <p>Tem certeza que deseja deletar esse produto:
                <span><strong>{{ produto }}</strong></span> ?</p>
        </div>
        <div class="modal-footer">
            <form action="{% url 'modal-remove-produto' produto.id %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Sim</button>
            </form>
            <button type="button" class="btn btn-info" data-dismiss="modal">Não</button>
        </div>
    </div>
</div>