api/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import ProdutoViewSet, PedidoViewSet, CarrinhoPedidoViewSet, VendaViewSet, CarrinhoVendaViewSet, \
    get_detail_produtos, api_home, ProdutoListApi, post_realiza_vendas, post_realiza_compras

router = routers.DefaultRouter()
router.register('produto', ProdutoViewSet)
router.register('pedido', PedidoViewSet)
router.register('carrinho-pedido', CarrinhoPedidoViewSet)
router.register('venda', VendaViewSet)
router.register('carrinho-venda', CarrinhoVendaViewSet)

urlpatterns = [
    path('drf/', include(router.urls)),
    path('', api_home, name='api_http'),
    path('produtos/', ProdutoListApi.as_view(), name='produto'),
    path('produto/<str:pk>', get_detail_produtos, name='get_produto'),
    path('produto/realiza_vendas/', post_realiza_vendas, name='post_realiza_vendas'),
    path('produto/realiza_compras/', post_realiza_compras, name='post_realiza_compras'),
    path('produto/', get_detail_produtos, name='get_produto'),
    path('api-auth/', include('rest_framework.urls'))

]

controle_vendas/urls.py
from django.urls import path
from .views import appvendas, lista_vendas, detalhe_venda

urlpatterns = [
    path('app-vendas/', appvendas, name="appvendas"),
    path('lista-vendas/', lista_vendas, name="lista-vendas"),
    path('detalhe-venda/<int:pk>', detalhe_venda, name='detalhe_venda'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import settings  # visualizar img
from django.conf.urls.static import static  # visualizar img

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('interfaces.urls')),
    path('api-rest/', include('api.urls')),
    path('vendas/', include('controle_vendas.urls')),
    path('pedidos/', include('controle_pedidos.urls')),
    path('produtos/', include('controle_estoque.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

controle_vendas/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import User
from controle_usuarios.models import Funcionario
from core.utils import STATUS_VENDA_CHOICES, PAGAMENTO_CHOICES


class CarrinhoVenda(models.Model):
    produto = models.ForeignKey("controle_estoque.Produto", on_delete=models.PROTECT)
    quantidade = models.IntegerField(default=1)
    venda = models.ForeignKey("Venda", on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.quantidade} peças de {self.produto.descricao}"

    def get_total_preco_produto(self):
        return self.quantidade * self.produto.preco_venda

    def get_total_faturado(self):
        return (self.quantidade * self.produto.preco_venda) - (self.quantidade * self.produto.preco_compra)


class Venda(models.Model):
    descricao = models.CharField('Descrição da Venda', max_length=50, blank=True, null=True)
    status = models.SmallIntegerField('Status', choices=STATUS_VENDA_CHOICES, default=1)
    caixa = models.ForeignKey(Funcionario, on_delete=models.PROTECT, related_name='venda_caixa',
                              verbose_name='Operador/Caixa', help_text="Caixa que está efetuando a venda")
    vendedor = models.ForeignKey(Funcionario, on_delete=models.PROTECT, related_name='venda_vendedor',
                                 verbose_name="Vendedor", help_text="Vendedor que atendeu o cliente")
    nota_fiscal = models.FileField('Nota Fiscal Eletronica', upload_to='controle_pedidos/NFE', blank=True, null=True)
    cpf = models.CharField('CPF', null=True, blank=True, max_length=11, help_text='Preencha o campo apenas com números.', validators=[
        RegexValidator(r'^\d{11,11}$', message='Por favor, não insira letras, " . " e " - " no campo abaixo.')])

    desconto = models.DecimalField('Desconto', decimal_places=2, max_digits=12, default=0,
                                   help_text="Digite o valor de desconto da venda, exemplo R$ 10,00")
    forma_pagto = models.SmallIntegerField("Forma De Pagamento", choices=PAGAMENTO_CHOICES)
    valor_total_venda = models.DecimalField('Valor Total da Venda', decimal_places=2, max_digits=12, default=0)
    ativo = models.BooleanField(default=True)
    criado_em = models.DateTimeField('Venda Realizada Em', auto_now_add=True)
    criado_por = models.ForeignKey(User, on_delete=models.PROTECT, related_name='venda_criadopor', editable=False)
    atualizado_por = models.ForeignKey(User, on_delete=models.PROTECT,
                                       related_name='venda_atualizado_por', editable=False, null=True, blank=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Venda'
        verbose_name_plural = 'Vendas'
        ordering = ['-id']

    def __str__(self):
        return f'{self.id}'

    def calc_total(self):
        total = 0
        for order_item in CarrinhoVenda.objects.filter(venda_id=self.id):
            total += order_item.get_total_preco_produto()
        return total

    def calc_faturamento(self):
        total = 0
        for order_item in CarrinhoVenda.objects.filter(venda_id=self.id):
            total += order_item.get_total_faturado()
        return total

    def save(self, *args, **kwargs):
        self.valor_total_venda = self.calc_total()
        super(Venda, self).save(*args, **kwargs)

    def get_produtos_vendidos(self):
        queryset = []
        for produto in CarrinhoVenda.objects.filter(venda=self):
            queryset.append(produto.produto)
        return queryset

    def get_valores_produtos_vendidos(self):
        queryset = {}
        for produto in CarrinhoVenda.objects.filter(venda=self):
            queryset.update({"produto": produto.produto, "preco": produto.produto.preco_venda})
        return queryset

controle_vendas/forms.py
from django import forms
from .models import Venda


class VendaForm(forms.ModelForm):
    class Meta:
        model = Venda
        fields = ['forma_pagto', 'vendedor']
        widgets = {
            'forma_pagto': forms.Select(attrs={
                'class': 'form-control',
                'id': 'pagamento',
            }),
            'vendedor': forms.Select(attrs={
                'class': 'form-control',
                'id': 'vendedor',
            })
        }

controle_vendas/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test
from controle_estoque.models import Produto
from .models import Venda
from .forms import VendaForm
from dateutil.parser import parse
from datetime import timedelta


@login_required()
@user_passes_test(lambda u: u.funcionario.is_manager_or_cashier(), login_url="/", redirect_field_name=None)
def appvendas(request):
    context = {
        'form': VendaForm(),
        'produtos': Produto.objects.all(),
        "active": "app-vendas"
    }
    return render(request, 'app_venda.html', context)


@login_required()
@user_passes_test(lambda u: u.funcionario.is_manager_or_analyst_or_cashier_or_seller(), login_url="/", redirect_field_name=None)
def lista_vendas(request):
    periodo = Venda.objects.all()
    data_inicial = request.GET.get('data_inicial')
    data_final = request.GET.get('data_final')

    if data_inicial and data_final:
        data_final = parse(data_final) + timedelta(1)
        periodo = Venda.objects.filter(ativo=True, criado_em__range=[data_inicial, data_final])

    context = {
        "vendas": periodo,
        "active": "lista-vendas",
    }
    return render(request, 'vendas.html', context)


@login_required()
@user_passes_test(lambda u: u.funcionario.is_manager_or_analyst_or_cashier_or_seller(), login_url="/", redirect_field_name=None)
def detalhe_venda(request, pk):
    venda = Venda.objects.get(pk=pk)
    produtos = venda.carrinhovenda_set.all()
    context = {
        'venda': venda,
        'produtos': produtos,
    }
    return render(request, 'modal_detalhe_venda.html', context)

controle_vendas/templates/app_venda.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
    <div id="vue-app">
        <div class="card">
            <div class="card-header text-center mt-2">
                <h2 class="card-text">App de Venda</h2>
            </div>
            <div class="card-body">
                <div class="alert-warning" v-if="errors">

                </div>
                <form @submit.prevent="add_produto" name="produtos_comprados">
                    {% csrf_token %}
                    <div class="col-sm-12 padding-off">
                        <div class="row justify-content-center" v-if="errors.length" v-for="error in errors">
                            <div class="col-sm-5">
                                <div class="alert alert-info alert-dismissible fade show" role="alert">
                                    <span class="alert-text"><strong>Atenção</strong> [[error]]</span>
                                </div>
                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <div class="col-3">
                                <div class="form-group-inline">
                                    <label class="sr-only" for="Produto"></label>
                                    <input type="text" id="Produto" name="produto_ean"
                                           class="form-control" placeholder="Digite o EAN do produto"
                                           v-model="produto_ean" maxlength="13"
                                           data-ls-module="charCounter"/>
                                </div>
                            </div>
                            <div class="col-1">
                                <div class="form-group-inline">
                                    <label class="sr-only" for="quantidade"></label>
                                    <input type="text" id="quantidade" name="newDomain"
                                           class="form-control" v-model="quantidade"/>
                                </div>
                            </div>
                            <div class="col-1 ">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-success btn-block">
                                        <i aria-hidden="true" class="fa fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>

                <div class="col-sm-12 pt-5 mb-lg-5">
                    <template v-if="produtos.length">
                        <div class="card-header text-center">

                            <h2>Lista de produtos selecionados:</h2>
                        </div>
                        <table class="table table-responsive mt-5">
                            <thead class="thead-active text-muted">
                            <tr>
                                <th scope="col">Produtos</th>
                                <th scope="col">Categoria</th>
                                <th scope="col">Subcategoria</th>
                                <th scope="col">Tamanho</th>
                                <th scope="col">Quantidade</th>
                                <th scope="col">Cor</th>
                                <th scope="col">Genero</th>
                                <th scope="col">Codigo de Barras</th>
                                <th scope="col">Em estoque</th>
                                <th scope="col">Preço</th>
                                <th scope="col">Remover</th>
                            </tr>
                            </thead>
                            <tbody>
                            <template v-for="produto in produtos.slice().reverse()">
                                <tr>
                                    <td>[[ produto.produto.descricao ]]</td>
                                    <td>[[ produto.produto.nome_categoria ]]</td>
                                    <td>[[ produto.produto.nome_subcategoria ]]</td>
                                    <td>[[ produto.produto.tamanho ]]</td>
                                    <td>[[ produto.quantidade ]]</td>
                                    <td>[[ produto.produto.cor ]]</td>
                                    <td>[[ produto.produto.genero ]]</td>
                                    <td>[[ produto.produto.ean ]]</td>
                                    <td>[[ produto.produto.total_pecas ]]</td>
                                    <td>[[ (produto.produto.preco_venda * produto.quantidade).toLocaleString(
                                        'pt-br',{style: 'currency', currency: 'BRL'}) ]]
                                    </td>
                                    <td>
                                        <button @click="remove_produto(produto)" class="btn btn-sm btn-danger">
                                            <i aria-hidden="true" class="fa fa-times"></i>
                                        </button>
                                    </td>
                                </tr>

                            </template>
                            </tbody>
                        </table>
                        <hr/>
                        <div class="form-group mt-lg-5">
                            <div class="form-row align-items-center justify-content-center">
                                <div class="col-3" style="text-align: center">
                                    <label for="vendedor">Vendedor</label>
                                    {% render_field form.vendedor v-model="vendedor" %}
                                </div>
                                <div class="col-3"></div>
                                <div class="col-3" style="text-align: center">
                                    <label for="pagamento">Forma de Pagamento</label>
                                    {% render_field form.forma_pagto v-model="formaPagamento" %}
                                </div>
                            </div>
                            <div class="form-row mt-5 align-items-center justify-content-center">
                                <div class="col-3 inline-block text-center align-bottom">
                                    <input type="checkbox" class="custom-control-input" id="cpf" v-model="cpf">
                                    <label class="custom-control-label" for="cpf">Adicionar CPF</label>
                                </div>
                                <div class="col-3"></div>
                                <div class="col-3" style="text-align: center">
                                    <template v-if="cpf">
                                        <label for="numerocpf">CPF</label>
                                        <input type="text" class="form-control cpf" id="numerocpf" name="numerocpf"
                                               maxlength="13" v-model="numCpf">
                                    </template>
                                </div>
                            </div>
                        </div>
                    </template>
                </div>
                <div class="form-row mt-5 align-items-center justify-content-center">
                    <div class="form-group">
                        <h3>Valor total: [[ valor_total.toLocaleString(
                            'pt-br',{style: 'currency', currency: 'BRL'}) ]]</h3>
                        <button @click="realiza_venda" class="btn btn-success mr-5">
                            Realizar Venda
                            <i aria-hidden="true" class="fas fa-store ml-2"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block extrajs %}
    <script src="{% static 'js/appvenda.js' %}"></script>
{% endblock %}

controle_vendas/templates/modal_detalhe_venda.html
{% load static %}
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header text-center">
            <h3 class="modal-title">Venda {{ venda }}</h3>
            <button type="button" class="close" data-dismiss="modal">
                <span class="text-danger">x</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="container mt-lg-4">
                <div class="col-md-12">
                    <div class="row mt-lg-3">
                        <div class="col-md-6 mb-4">
                            <h4>Status</h4>
                            <p>{{ venda.get_status_display }}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Descrição</h4>
                            {% if venda.descricao == None %}
                                <p>Sem Descrição</p>
                            {% else %}
                                <p>{{ venda.descricao }}</p>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Caixa</h4>
                            <p>{{ venda.caixa }}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Vendedor</h4>
                            <p>{{ venda.vendedor }}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>CPF Consumidor</h4>
                            {% if venda.cpf == "" %}
                                <p>CPF não informado</p>
                            {% else %}
                                <p>{{ venda.cpf }}</p>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Nota Fiscal</h4>
                            {% if venda.nota_fiscal %}
                                <span class="text-center"><i class="fa fa-check-circle text-success"></i></span>
                            {% else %}
                                <span class="text-center"><i class="fa fa-times-circle text-danger"></i></span>
                            {% endif %}
                            <p>{{ venda.nota_fiscal }}</p>
                        </div>
                    </div>
                    <div class="row mt-lg-3">
                        <div class="col-md-6 mb-4">
                            <h4>Data da Venda</h4>
                            <p>{{ venda.criado_em }}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Desconto</h4>
                            <p>{{ venda.desconto }}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Valor Total da Venda</h4>
                            <p>R$ {{ venda.valor_total_venda }}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Forma de Pagamento</h4>
                            <p>{{ venda.get_forma_pagto_display }}</p>
                        </div>
                        <div class="col-md-6 mb-4">
                            <h4>Criado Por</h4>
                            <p>{{ venda.criado_por|title }}</p>
                        </div>
                    </div>
                    {% if produtos %}
                        <div class="row mt-lg-12">
                            <h4 class="text-center">Produtos</h4>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead class="table" style="background-color: #5e72e4; color: #fff">
                                    <tr>
                                        <th>SKU</th>
                                        <th>Cor</th>
                                        <th>Fornecedor</th>
                                        <th>Preço de Venda</th>
                                        <th>Quantidade</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for produto in produtos %}
                                        <tr>
                                            <td>{{ produto.produto.sku }}</td>
                                            <td>{{ produto.produto.cor }}</td>
                                            <td>{{ produto.produto.fornecedor }}</td>
                                            <td>{{ produto.produto.preco_venda }}</td>
                                            <td>{{ produto.quantidade }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    {% else %}
                        <h4>Sem produtos cadastrados para esta venda</h4>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="modal-footer mb-5">
            <div class="row mt-5" style="position: absolute; right: 2em">
                <button type="submit" class="btn btn-info mr-2" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

controle_vendas/templates/vendas.html
{% extends 'base.html' %}
{% block content %}
    <div class="card">
        <div class="card-header">
            <h3 class="text-darker">Listagem de Vendas</h3>

            <div class="col-md-auto">
                <form class="form-inline my--2 pull-right">
                    <div class="col-md-auto">
                        <label class="text-darker">Data Inicial</label>
                        <input class="form-control" name="data_inicial" type="date"/>
                    </div>
                    <div class="col-md-auto">
                        <label class="text-darker">Data Final</label>
                        <input class="form-control" name="data_final" type="date"/>
                    </div>
                    <div style="padding-top: 25px">
                        <button class="btn btn-primary m-2 my-sm-0" type="submit">Filtrar Data</button>
                    </div>
                </form>
            </div>


        </div>
        <div class="card-body">
            <table class="table table-striped table-responsive-lg" id="table_vendas">
                <thead class="thead-light">
                <tr>
                    <th class="text-center">Vendas</th>
                    <th>Status</th>
                    <th>Caixa</th>
                    <th>Vendedor</th>
                    <th>Desconto</th>
                    <th>Valor Total da Venda</th>
                    <th>Forma de Pagamento</th>
                    <th>Criado Em</th>
                    <th>Descrição</th>
                </tr>
                </thead>
                <tbody>
                {% for venda in vendas %}
                    <tr>
                        <td><a href="#"
                               onclick="open_modal_details('{% url 'detalhe_venda' venda.id %}')">Venda {{ venda }}</a>
                        </td>
                        <td> {{ venda.get_status_display }} </td>
                        <td> {{ venda.caixa }} </td>
                        <td> {{ venda.vendedor }} </td>
                        <td> {{ venda.desconto }} </td>
                        <td> R$ {{ venda.valor_total_venda }} </td>
                        <td> {{ venda.get_forma_pagto_display }} </td>
                        <td> {{ venda.criado_em }} </td>
                        {% if venda.descricao == None %}
                            <td>Sem descrição</td>
                        {% else %}
                            <td>{{ venda.descricao }}</td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="modal fade center" id="detail_modal" tabindex="-1" role="dialog"></div>
{% endblock %}
{% block extrajs %}
    <script>
        function open_modal_details(url) {
            $('#detail_modal').focus().load(url, function () {
                $(this).modal('show');
            })
        }

        $(document).ready(function () {
            $("#table_vendas").DataTable({
                "language": {
                    "lengthMenu": "Listando _MENU_ registro por pagina",
                    "zeroRecords": "Nenhum registro localizado",
                    "info": "Pagina _PAGE_ de _PAGES_",
                    "infoEmpty": "Nenhum registro disponível",
                    "infoFiltered": "(Filtrado de _MAX_ total resultados)",
                    "search": "Buscar",
                    "paginate": {
                        "first": "Primeira",
                        "last": "Ultima",
                        "next": "Proxima",
                        "previous": "Anterior"
                    },
                }
            });
        });
    </script>
{% endblock %}